### PR TITLE
4 write a readme

### PR DESCRIPTION
**Pull request by SanderDevisscher**
@PietrH maybe better to merge all changes to the readme into 1 branch.

### CODE REVIEW

**Comment by SanderDevisscher** [comment]
nvm this is a total overwrite I'll close both PRS and start a new one

**Comment by PietrH** [comment]
I'm sorry, I didn't notice you got started on this. I'll back off, go ahead.

**Comment by PietrH** [comment]
This PR is much better than the one I just opened. I'm alright with just merging this one into main.

**Comment by PietrH** [comment]
Whoops, my bad.

**Comment by SanderDevisscher** [comment]
No problem 😉

**Pull request closed without merging**
