### PR TITLE
Use `changer::changer` to rename package

### LINKED ISSUE #11: Come up with a better name for this package
This package is more general than just vespa-watch, it'll work just as well for other domains on iAsset. And in fact, we are planning to use it for our other project on our domain as well. 

I'm open to any suggestions!

### PR DESCRIPTION
**Pull request by PietrH**
Me and @SanderDevisscher have decided to rename the repo, and package from `vespawatchr` to `iassetR` because while we currently are writing this in the scope of vespawatch, we want to keep the package general enough to be used by any iAsset user. Any vespawatch specific code should go in vespawatch specific repo's. 

@SanderDevisscher , I'm setting you as reviewer as soon as this is ready for review. But I would like to merge it into main myself. 

From this merge onwards, anyone developing on this package will have to update their local versions to the new repo and project. You can do this in Git CLI or Github Desktop (under repository), but I usually find it easier to just delete my local copy and to clone a new one.

### CODE REVIEW

**Comment by PietrH** [comment]
Sander, here is what I think you need to test:

- Does this break you local version of the package (yes!): can you get it to work again by cloning
- Does this branch pass R CMD CHECK for you, this is under the build tab of RStudio
- Can you get any function to break that wasn't already broken after this change
- Does this break the other (hopefully very experimental) scripts that you have that are dependent on `iassetR`
- Did I miss anything while renaming the package? 


Also: 

How are we going to handle references to vespawatch going forward, ie in the function documentation and examples. In default values etc. I say we keep them in for now, but it might be a pain removing them later. It's a balance of user friendliness towards ourselves as users, and possible other users that don't know about vespawatch in the future. 

We might want to avoid setting default values to vespawatch defaults, but it would be handy for us... We could also handle this with System ENV parameters, but I always find that less user friendly when I'm using a new package since this is stuff I can't really see in my IDE. What do you think?

**Comment by SanderDevisscher** [comment]
@PietrH I can plan to test this by this wednesday (29/11) ok?

**Comment by PietrH** [comment]
Alright, It's better not to merge anything to main in the meantime. I want any merge conflicts to occur with these changes already present in the main branch.

**Comment by SanderDevisscher** [comment]
@PietrH shouldn't the .proj be renamed as well ?

**Review by SanderDevisscher — APPROVED** [review]
─ R CMD check results  iassetR 0.0.0.─
Duration: 17.7s

0 errors ✔ | 0 warnings ✔ | 0 notes ✔

R CMD check succeeded

After cloning & building the package from this branch just changing `library(vespawatchr)` to `library(iassetR)`  in my experimental scripts seems to work like a charm. 

Are there any more tests I need to do before merging ?

**Comment by PietrH** [comment]
Nope, all good. I'll merge this one myself!

**Pull request merged**
