### PR TITLE
4 write a readme

### LINKED ISSUE #4: write a readme
Ideally we'd also add a vignette on how to use the package, but this is something for beyond v0.1.

Things to mention in the readme:

- [ ] Why did we make this package, mention that we want it to be broadly applicable for all iAsset users, but that our focus is currently on Vespa-Watch and RIPARIAS
- [ ] What is the scope of the package (currently reading records, not changing them)
- [ ] Refer to the [iAsset API documentation](https://api.iasset.nl/)
- [ ] What can you do with the package; functions; `get_access_token()`  for a token, `get_records()` to get records and `get_fields()` to get information about the fields
- [ ] (optional) Mention Vespa-Watch as funding? 
- [ ] An example (**excluding passwords, usernames or keys!**) or how to get records out of iAsset

### PR DESCRIPTION
**Pull request by SanderDevisscher**

### CODE REVIEW

**Review by PietrH — APPROVED** [review]
Looks great

**Comment by PietrH** [comment]
@SanderDevisscher Go ahead and Merge!

**Comment by PietrH** [comment]
We might want to add an example actually, but this can be done a bit later as well.

**Comment by SanderDevisscher** [comment]
I'll merge this PR but keep the branch open to add an example

**Comment by PietrH** [comment]
> I'll merge this PR but keep the branch open to add an example

Just start a new branch, no harm in it

**Pull request merged**
