### PR TITLE
21 convert data from answercode to answer

### LINKED ISSUE #1: get_records(): handle list columns
Currently we have a few multivalue in the API output, we still need to handle these more elegantly before we can output to a tibble. 

Currently we have explored` tibble::enframe()`, and tidyr::pivot_wider()

```r
res %>% httr::content() %>% 
  purrr::pluck("returndata") %>% 
  head(5) %>% 
  purrr::map(~purrr::pluck(.x, "data")) %>%
  # purrr::map(~purrr::map_dfc(.x, function(element){element}))
  purrr::map(~tibble::enframe(.x)) %>% 
  purrr::map_dfr(~ tidyr::pivot_wider(.x, names_from = name))
```

But I personally think it should probably be handled with a combination of purrr::map_dfc and purrr::map_dfr

### LINKED ISSUE #21: Convert data from answercode to answer
Currently fields of `fieldtype == "select" or "radio"` (maybe also others) contain a code related to their answer in the output of `get_records`. It would be usefull to have the actual answers instead. 
The actual answers can be found in the "options" column of `get_fields` "fields" slot. 
There is no data column present to link the answer with the answer code. 

**Pay attention:** the content of the column "fieldlabel" is not snakecase while the column names from `get_records` are!
**Pay attention:** some select/radio columns from `get_records` are of class "list" these merit a different approach!

Some testing from myself:
https://github.com/inbo/aspbo/blob/ae995deb42686abc644d6e02f290f78c4204d1d8/src/get_data_from_iAsset.Rmd#L27-L49

### PR DESCRIPTION
**Pull request by PietrH**
## Todo

- [x] see if `select_inspectors` is recoded
~~- [ ] Add tests for `get_records()` especially regarding recoding~~
- [x] create issue for optionally returning same column names as in iAsset, but set to default `FALSE`
- [x] Add issue for bad failure state on bad username
- [x] Remove test infrastructure

### CODE REVIEW

**Comment by SanderDevisscher** [comment]
@PietrH can I test this ?

**Comment by SanderDevisscher** [comment]
PS it works

**Comment by PietrH** [comment]
Thanks for having a look at it Sander, I'm not ready with this branch yet. I've added a todo list to this PR. 

Sorry it's been dragging on. Do you have any experience writing tests with [testthat](https://testthat.r-lib.org/)?

**Comment by SanderDevisscher** [comment]
Sorry no experience with testthat, however I'm willing to learn.

**Comment by PietrH** [comment]
No worries, we can get together about that at some point. There is some information about it in the R packages book: https://r-pkgs.org/testing-basics.html

**Comment by PietrH** [comment]
I'll take care of the unit tests for this PR though, don't worry!

**Comment by SanderDevisscher** [comment]
> No worries, we can get together about that at some point. There is some information about it in the R packages book: https://r-pkgs.org/testing-basics.html

thanks

**Comment by PietrH** [comment]
The failure state when you enter the wrong username isn't very elegant: 

```R
get_records(access_token = get_access_token(username = "pieter.huybrechts@inbo.be"))

#>Error: access_token is not a string (a length one character vector).
```

**Comment by PietrH** [comment]
Select fields are recoded, currently `radio` and `select` fields are treated equally.

**Comment by PietrH** [comment]
I've decided tests are for a seperate PR, in the context of #7 because it'll require a bit more tooling. I'd like to avoid mocking or vcr if at all possible.

**Comment by PietrH** [comment]
> The failure state when you enter the wrong username isn't very elegant:
> 
> ```r
> get_records(access_token = get_access_token(username = "pieter.huybrechts@inbo.be"))
> 
> #>Error: access_token is not a string (a length one character vector).
> ```

#27

**Comment by PietrH** [comment]
Issue for optionally returning verbatim field names as iAsset: #28

**Comment by PietrH** [comment]
> PS it works

I'm interpreting this as a positive review, and merging to main. If it's broken, please open an issue.

**Pull request merged**
