### PR TITLE
Add basic functionality of `get_records()`

### LINKED ISSUE #2: attatch field names from get_fields() to output of get_records()
I currently fetch the field names, but we want to attach these to the output of the tibble

### LINKED ISSUE #3: httr2 doesn't seem to work for get_records(), but httr does
I'm used to writing my httr2 requests like this:

```r
get_records <- function(inspection_name = "Vespa-Watch",
                        access_token = get_access_token(quiet = TRUE)) {
  # check input params
  assertthat::assert_that(assertthat::is.string(access_token))
  assertthat::assert_that(assertthat::is.string(inspection_name))
  # get the inspection_id for the custom inspection
  inspection_fields <- get_fields(access_token = access_token,
                                  name = inspection_name)
  # build a request and perform it
  get_records_request <-
    httr2::request("https://api.iasset.nl/getCustomInspections") %>%
    httr2::req_body_form(
      access_token = access_token,
      "inspection_ids[0]" = inspection_fields$id,
      version = "9.7"
    )
}
```

but it doesn't work, while this in httr does:

```r

body = list(
  'access_token' = access_token,
  'version' = '9.7',
  'inspection_ids[0]' = inspection_fields$id
)

res <-
  httr::VERB(
    "POST",
    url = "https://api.iasset.nl/getCustomInspections",
    body = body,
    encode = 'multipart'
  )

# cat(content(res, 'text'))

res %>% httr::content()
```

- [ ] is this a bug in httr2 ?
- [ ] Is my httr2 code wrong?

### PR DESCRIPTION
**Pull request by PietrH**
`get_records()` is now in a minimally functional state.

What works:

- [x] You can get all records for a custom inspection (i.e. `Vespa-Watch`
- [x] All columns get the same labels as they have in the interface
- [x] These labels are converted into r friendly equivalents, so underscores instead of spaces
- [x] The package will retry 3 times if the request fails

What is missing: 

- [ ] Any filtering like `2. Valideren`
- [ ] The function is completely uncovered by unit tests
- [ ] All columns are imported as character strings, we have column class information from `get_fields()`
- [ ] We could convert some values to their R equivalent, for example: `toestemming_gegevensgebruik == "on"` might make more sense as `toestemming_gegevensgebruik == TRUE`, we could use date and time fields for `datum_tijd_registratie` and `datum_observatie` to save users on having to to these conversions themselves. 
- [ ] List columns are still present in the output
- [ ] There are no elegant failure states for a request that goes wrong in any way
- [ ] The function takes a while to run, but has no progress reporting at all

## Questions

- Howmany records are we expecting? I'm getting around 17994 at the moment. Is that in the right ballpark? 
- We are expecting some values to me missing, some even most of the time. But I don't know what is expected to be mostly filled in and what is not. Does this look about right? 

https://drive.google.com/file/d/1a8bVYH_SYoZklF8xKLRBixdFGvlfgGh-

### CODE REVIEW

**Comment by PietrH** [comment]
An issue remains where only one image url seems to be fetched for all records

**Comment by PietrH** [comment]
> An issue remains where only one image url seems to be fetched for all records

False alarm, I was looking at `foto_bestrijding` which only has a value for a single record.

**Comment by PietrH** [comment]
@SanderDevisscher Is there any _must have_ functionality missing from `get_records()`, or can we go ahead and merge into main and work on the other features independently? 

Feel free to try it out on this branch with: `get_records(access_token = get_access_token(username = "your_username"))`

You'll need to install the package first, you can do this by hitting the Install button, under Build in RStudio. This should be visible if you load the project included in this repo. Let me know if you need any help! :wink:

**Comment by PietrH** [comment]
@SanderDevisscher Is there any _must have_ functionality missing from `get_records()`, or can we go ahead and merge into main and work on the other features independently? 

Feel free to try it out on this branch with: `get_records(access_token = get_access_token(username = "your_username"))`

You'll need to install the package first, you can do this by hitting the Install button, under Build in RStudio. This should be visible if you load the project included in this repo. Let me know if you need any help! :wink:

**Comment by SanderDevisscher** [comment]
Still in draft, should I wait ?

**Comment by PietrH** [comment]
Sorry, no go ahead

**Review by SanderDevisscher — APPROVED** [review]
Function works as wanted.

**Pull request merged**
